services:
  backend:
    container_name: backend_falcon
    build: 
      context: .
      dockerfile: Dockerfile
    command: nodemon --watch /usr/src/backend -e js app.js
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend_falcon
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_TARGET=http://backend_falcon:3000
